-- ============================================================
-- Juzgo — Plans page migration + dummy seed
-- Run in Supabase SQL Editor (single run, idempotent-ish: see notes)
-- Aligns countries/esim_plans schema with src/pages/Plans.js,
-- then seeds 42 destinations + 3 regional/global bundles.
-- Package IDs match MOCK_PACKAGES in the claude-proxy worker 1:1.
-- ============================================================

-- ---------- 1. Schema migration (frontend expects these names) ----------
ALTER TABLE countries  RENAME COLUMN flag TO flag_emoji;
ALTER TABLE esim_plans RENAME COLUMN name TO plan_name;
ALTER TABLE esim_plans RENAME COLUMN duration_days TO validity_days;
ALTER TABLE esim_plans RENAME COLUMN price_usd TO price_sgd;  -- prices below are SGD
ALTER TABLE esim_plans ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
ALTER TABLE esim_plans ADD COLUMN IF NOT EXISTS package_id text UNIQUE;  -- links to worker/Airalo package id

-- ---------- 2. Public read access ----------
-- Plans.js reads both tables with the anon key. If RLS is enabled without
-- a SELECT policy, results are silently empty. These are safe public-catalogue reads.
ALTER TABLE countries  ENABLE ROW LEVEL SECURITY;
ALTER TABLE esim_plans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read countries"  ON countries;
DROP POLICY IF EXISTS "Public read esim_plans" ON esim_plans;
CREATE POLICY "Public read countries"  ON countries  FOR SELECT USING (true);
CREATE POLICY "Public read esim_plans" ON esim_plans FOR SELECT USING (true);

-- ---------- 3. Clean slate (tables are empty today; safe) ----------
DELETE FROM esim_plans;
DELETE FROM countries;

-- ---------- 4. Seed countries ----------
INSERT INTO countries (id, name, code, flag_emoji, region) VALUES
  (gen_random_uuid(), 'Singapore', 'SG', '🇸🇬', 'Asia'),
  (gen_random_uuid(), 'Japan', 'JP', '🇯🇵', 'Asia'),
  (gen_random_uuid(), 'South Korea', 'KR', '🇰🇷', 'Asia'),
  (gen_random_uuid(), 'Thailand', 'TH', '🇹🇭', 'Asia'),
  (gen_random_uuid(), 'Malaysia', 'MY', '🇲🇾', 'Asia'),
  (gen_random_uuid(), 'Indonesia', 'ID', '🇮🇩', 'Asia'),
  (gen_random_uuid(), 'Vietnam', 'VN', '🇻🇳', 'Asia'),
  (gen_random_uuid(), 'Philippines', 'PH', '🇵🇭', 'Asia'),
  (gen_random_uuid(), 'Taiwan', 'TW', '🇹🇼', 'Asia'),
  (gen_random_uuid(), 'Hong Kong', 'HK', '🇭🇰', 'Asia'),
  (gen_random_uuid(), 'China', 'CN', '🇨🇳', 'Asia'),
  (gen_random_uuid(), 'India', 'IN', '🇮🇳', 'Asia'),
  (gen_random_uuid(), 'Cambodia', 'KH', '🇰🇭', 'Asia'),
  (gen_random_uuid(), 'Sri Lanka', 'LK', '🇱🇰', 'Asia'),
  (gen_random_uuid(), 'Macau', 'MO', '🇲🇴', 'Asia'),
  (gen_random_uuid(), 'United Arab Emirates', 'AE', '🇦🇪', 'Middle East'),
  (gen_random_uuid(), 'Turkey', 'TR', '🇹🇷', 'Middle East'),
  (gen_random_uuid(), 'Qatar', 'QA', '🇶🇦', 'Middle East'),
  (gen_random_uuid(), 'Saudi Arabia', 'SA', '🇸🇦', 'Middle East'),
  (gen_random_uuid(), 'United Kingdom', 'GB', '🇬🇧', 'Europe'),
  (gen_random_uuid(), 'France', 'FR', '🇫🇷', 'Europe'),
  (gen_random_uuid(), 'Germany', 'DE', '🇩🇪', 'Europe'),
  (gen_random_uuid(), 'Italy', 'IT', '🇮🇹', 'Europe'),
  (gen_random_uuid(), 'Spain', 'ES', '🇪🇸', 'Europe'),
  (gen_random_uuid(), 'Portugal', 'PT', '🇵🇹', 'Europe'),
  (gen_random_uuid(), 'Netherlands', 'NL', '🇳🇱', 'Europe'),
  (gen_random_uuid(), 'Switzerland', 'CH', '🇨🇭', 'Europe'),
  (gen_random_uuid(), 'Austria', 'AT', '🇦🇹', 'Europe'),
  (gen_random_uuid(), 'Greece', 'GR', '🇬🇷', 'Europe'),
  (gen_random_uuid(), 'Ireland', 'IE', '🇮🇪', 'Europe'),
  (gen_random_uuid(), 'Poland', 'PL', '🇵🇱', 'Europe'),
  (gen_random_uuid(), 'Czechia', 'CZ', '🇨🇿', 'Europe'),
  (gen_random_uuid(), 'United States', 'US', '🇺🇸', 'Americas'),
  (gen_random_uuid(), 'Canada', 'CA', '🇨🇦', 'Americas'),
  (gen_random_uuid(), 'Mexico', 'MX', '🇲🇽', 'Americas'),
  (gen_random_uuid(), 'Brazil', 'BR', '🇧🇷', 'Americas'),
  (gen_random_uuid(), 'Australia', 'AU', '🇦🇺', 'Oceania'),
  (gen_random_uuid(), 'New Zealand', 'NZ', '🇳🇿', 'Oceania'),
  (gen_random_uuid(), 'Egypt', 'EG', '🇪🇬', 'Africa'),
  (gen_random_uuid(), 'South Africa', 'ZA', '🇿🇦', 'Africa'),
  (gen_random_uuid(), 'Morocco', 'MA', '🇲🇦', 'Africa'),
  (gen_random_uuid(), 'Kenya', 'KE', '🇰🇪', 'Africa'),
  (gen_random_uuid(), 'Asia (Regional — 14 countries)', 'ASIA', '🌏', 'Regional'),
  (gen_random_uuid(), 'Europe (Regional — 30 countries)', 'EURO', '🌍', 'Regional'),
  (gen_random_uuid(), 'Global (120+ countries)', 'GLOBAL', '🌐', 'Global');

-- NOTE: the three Regional/Global rows (codes ASIA, EURO, GLOBAL) are optional —
-- delete them if you want a countries-only dropdown:
--   DELETE FROM esim_plans WHERE country_id IN (SELECT id FROM countries WHERE code IN ('ASIA','EURO','GLOBAL'));
--   DELETE FROM countries WHERE code IN ('ASIA','EURO','GLOBAL');

-- ---------- 5. Seed plans (linked by country code) ----------
INSERT INTO esim_plans (id, country_id, plan_name, data_gb, validity_days, price_sgd, provider, is_active, package_id)
VALUES
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'SG'), '1GB · 7 Days', 1, 7, 5.0, 'Changi Connect', true, 'sg-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'SG'), '3GB · 15 Days', 3, 15, 9.0, 'Changi Connect', true, 'sg-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'SG'), '5GB · 30 Days', 5, 30, 14.0, 'Changi Connect', true, 'sg-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'SG'), '10GB · 30 Days', 10, 30, 22.0, 'Changi Connect', true, 'sg-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'JP'), '1GB · 7 Days', 1, 7, 6.0, 'Sakura Mobile', true, 'jp-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'JP'), '3GB · 15 Days', 3, 15, 12.0, 'Sakura Mobile', true, 'jp-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'JP'), '5GB · 30 Days', 5, 30, 18.0, 'Sakura Mobile', true, 'jp-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'JP'), '10GB · 30 Days', 10, 30, 29.0, 'Sakura Mobile', true, 'jp-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'JP'), 'Unlimited · 30 Days', 999, 30, 45.0, 'Sakura Mobile', true, 'jp-30days-unlimited'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'KR'), '1GB · 7 Days', 1, 7, 6.0, 'Seoul Connect', true, 'kr-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'KR'), '3GB · 15 Days', 3, 15, 11.5, 'Seoul Connect', true, 'kr-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'KR'), '5GB · 30 Days', 5, 30, 17.5, 'Seoul Connect', true, 'kr-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'KR'), '10GB · 30 Days', 10, 30, 27.5, 'Seoul Connect', true, 'kr-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'KR'), 'Unlimited · 30 Days', 999, 30, 43.0, 'Seoul Connect', true, 'kr-30days-unlimited'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'TH'), '1GB · 7 Days', 1, 7, 4.0, 'ThaiFi', true, 'th-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'TH'), '3GB · 15 Days', 3, 15, 7.5, 'ThaiFi', true, 'th-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'TH'), '5GB · 30 Days', 5, 30, 11.5, 'ThaiFi', true, 'th-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'TH'), '10GB · 30 Days', 10, 30, 18.5, 'ThaiFi', true, 'th-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'TH'), 'Unlimited · 30 Days', 999, 30, 29.0, 'ThaiFi', true, 'th-30days-unlimited'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MY'), '1GB · 7 Days', 1, 7, 4.0, 'Boleh Connect', true, 'my-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MY'), '3GB · 15 Days', 3, 15, 7.0, 'Boleh Connect', true, 'my-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MY'), '5GB · 30 Days', 5, 30, 11.0, 'Boleh Connect', true, 'my-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MY'), '10GB · 30 Days', 10, 30, 17.0, 'Boleh Connect', true, 'my-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ID'), '1GB · 7 Days', 1, 7, 4.0, 'Nusantara Net', true, 'id-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ID'), '3GB · 15 Days', 3, 15, 7.0, 'Nusantara Net', true, 'id-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ID'), '5GB · 30 Days', 5, 30, 11.0, 'Nusantara Net', true, 'id-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ID'), '10GB · 30 Days', 10, 30, 17.0, 'Nusantara Net', true, 'id-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'VN'), '1GB · 7 Days', 1, 7, 3.5, 'Saigon Signal', true, 'vn-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'VN'), '3GB · 15 Days', 3, 15, 6.5, 'Saigon Signal', true, 'vn-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'VN'), '5GB · 30 Days', 5, 30, 10.0, 'Saigon Signal', true, 'vn-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'VN'), '10GB · 30 Days', 10, 30, 16.0, 'Saigon Signal', true, 'vn-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'PH'), '1GB · 7 Days', 1, 7, 4.0, 'Isla Mobile', true, 'ph-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'PH'), '3GB · 15 Days', 3, 15, 7.5, 'Isla Mobile', true, 'ph-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'PH'), '5GB · 30 Days', 5, 30, 11.5, 'Isla Mobile', true, 'ph-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'PH'), '10GB · 30 Days', 10, 30, 18.5, 'Isla Mobile', true, 'ph-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'TW'), '1GB · 7 Days', 1, 7, 5.0, 'Formosa Link', true, 'tw-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'TW'), '3GB · 15 Days', 3, 15, 9.5, 'Formosa Link', true, 'tw-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'TW'), '5GB · 30 Days', 5, 30, 14.5, 'Formosa Link', true, 'tw-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'TW'), '10GB · 30 Days', 10, 30, 23.0, 'Formosa Link', true, 'tw-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'TW'), 'Unlimited · 30 Days', 999, 30, 36.0, 'Formosa Link', true, 'tw-30days-unlimited'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'HK'), '1GB · 7 Days', 1, 7, 5.0, 'Harbour Data', true, 'hk-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'HK'), '3GB · 15 Days', 3, 15, 10.0, 'Harbour Data', true, 'hk-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'HK'), '5GB · 30 Days', 5, 30, 15.0, 'Harbour Data', true, 'hk-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'HK'), '10GB · 30 Days', 10, 30, 24.0, 'Harbour Data', true, 'hk-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CN'), '1GB · 7 Days', 1, 7, 5.0, 'Panda Roam', true, 'cn-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CN'), '3GB · 15 Days', 3, 15, 9.5, 'Panda Roam', true, 'cn-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CN'), '5GB · 30 Days', 5, 30, 14.5, 'Panda Roam', true, 'cn-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CN'), '10GB · 30 Days', 10, 30, 23.0, 'Panda Roam', true, 'cn-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'IN'), '1GB · 7 Days', 1, 7, 3.0, 'Lotus Telecom', true, 'in-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'IN'), '3GB · 15 Days', 3, 15, 6.0, 'Lotus Telecom', true, 'in-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'IN'), '5GB · 30 Days', 5, 30, 9.5, 'Lotus Telecom', true, 'in-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'IN'), '10GB · 30 Days', 10, 30, 15.0, 'Lotus Telecom', true, 'in-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'KH'), '1GB · 7 Days', 1, 7, 4.0, 'Angkor Air Data', true, 'kh-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'KH'), '3GB · 15 Days', 3, 15, 7.0, 'Angkor Air Data', true, 'kh-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'KH'), '5GB · 30 Days', 5, 30, 11.0, 'Angkor Air Data', true, 'kh-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'KH'), '10GB · 30 Days', 10, 30, 17.0, 'Angkor Air Data', true, 'kh-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'LK'), '1GB · 7 Days', 1, 7, 3.5, 'Ceylon Cell', true, 'lk-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'LK'), '3GB · 15 Days', 3, 15, 6.5, 'Ceylon Cell', true, 'lk-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'LK'), '5GB · 30 Days', 5, 30, 10.0, 'Ceylon Cell', true, 'lk-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'LK'), '10GB · 30 Days', 10, 30, 16.0, 'Ceylon Cell', true, 'lk-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MO'), '1GB · 7 Days', 1, 7, 5.0, 'Lotus Bridge Mobile', true, 'mo-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MO'), '3GB · 15 Days', 3, 15, 9.5, 'Lotus Bridge Mobile', true, 'mo-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MO'), '5GB · 30 Days', 5, 30, 14.5, 'Lotus Bridge Mobile', true, 'mo-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MO'), '10GB · 30 Days', 10, 30, 23.0, 'Lotus Bridge Mobile', true, 'mo-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'AE'), '1GB · 7 Days', 1, 7, 6.5, 'Falcon Net', true, 'ae-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'AE'), '3GB · 15 Days', 3, 15, 12.5, 'Falcon Net', true, 'ae-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'AE'), '5GB · 30 Days', 5, 30, 19.0, 'Falcon Net', true, 'ae-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'AE'), '10GB · 30 Days', 10, 30, 30.0, 'Falcon Net', true, 'ae-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'AE'), 'Unlimited · 30 Days', 999, 30, 47.0, 'Falcon Net', true, 'ae-30days-unlimited'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'TR'), '1GB · 7 Days', 1, 7, 4.5, 'Bosphorus Mobile', true, 'tr-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'TR'), '3GB · 15 Days', 3, 15, 8.5, 'Bosphorus Mobile', true, 'tr-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'TR'), '5GB · 30 Days', 5, 30, 13.0, 'Bosphorus Mobile', true, 'tr-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'TR'), '10GB · 30 Days', 10, 30, 20.5, 'Bosphorus Mobile', true, 'tr-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'QA'), '1GB · 7 Days', 1, 7, 6.5, 'Pearl Data', true, 'qa-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'QA'), '3GB · 15 Days', 3, 15, 12.5, 'Pearl Data', true, 'qa-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'QA'), '5GB · 30 Days', 5, 30, 19.0, 'Pearl Data', true, 'qa-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'QA'), '10GB · 30 Days', 10, 30, 30.0, 'Pearl Data', true, 'qa-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'SA'), '1GB · 7 Days', 1, 7, 6.0, 'Oasis Roam', true, 'sa-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'SA'), '3GB · 15 Days', 3, 15, 11.5, 'Oasis Roam', true, 'sa-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'SA'), '5GB · 30 Days', 5, 30, 17.5, 'Oasis Roam', true, 'sa-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'SA'), '10GB · 30 Days', 10, 30, 27.5, 'Oasis Roam', true, 'sa-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'GB'), '1GB · 7 Days', 1, 7, 5.5, 'BritConnect', true, 'gb-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'GB'), '3GB · 15 Days', 3, 15, 10.5, 'BritConnect', true, 'gb-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'GB'), '5GB · 30 Days', 5, 30, 16.0, 'BritConnect', true, 'gb-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'GB'), '10GB · 30 Days', 10, 30, 25.5, 'BritConnect', true, 'gb-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'GB'), 'Unlimited · 30 Days', 999, 30, 39.5, 'BritConnect', true, 'gb-30days-unlimited'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'FR'), '1GB · 7 Days', 1, 7, 5.5, 'Lumière Mobile', true, 'fr-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'FR'), '3GB · 15 Days', 3, 15, 10.5, 'Lumière Mobile', true, 'fr-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'FR'), '5GB · 30 Days', 5, 30, 16.0, 'Lumière Mobile', true, 'fr-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'FR'), '10GB · 30 Days', 10, 30, 25.5, 'Lumière Mobile', true, 'fr-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'FR'), 'Unlimited · 30 Days', 999, 30, 39.5, 'Lumière Mobile', true, 'fr-30days-unlimited'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'DE'), '1GB · 7 Days', 1, 7, 5.5, 'Alpen Data', true, 'de-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'DE'), '3GB · 15 Days', 3, 15, 10.5, 'Alpen Data', true, 'de-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'DE'), '5GB · 30 Days', 5, 30, 16.0, 'Alpen Data', true, 'de-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'DE'), '10GB · 30 Days', 10, 30, 25.5, 'Alpen Data', true, 'de-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'IT'), '1GB · 7 Days', 1, 7, 5.0, 'Vespa Net', true, 'it-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'IT'), '3GB · 15 Days', 3, 15, 10.0, 'Vespa Net', true, 'it-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'IT'), '5GB · 30 Days', 5, 30, 15.0, 'Vespa Net', true, 'it-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'IT'), '10GB · 30 Days', 10, 30, 24.0, 'Vespa Net', true, 'it-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ES'), '1GB · 7 Days', 1, 7, 5.0, 'Sol Mobile', true, 'es-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ES'), '3GB · 15 Days', 3, 15, 10.0, 'Sol Mobile', true, 'es-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ES'), '5GB · 30 Days', 5, 30, 15.0, 'Sol Mobile', true, 'es-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ES'), '10GB · 30 Days', 10, 30, 24.0, 'Sol Mobile', true, 'es-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'PT'), '1GB · 7 Days', 1, 7, 5.0, 'Atlantico Cell', true, 'pt-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'PT'), '3GB · 15 Days', 3, 15, 9.5, 'Atlantico Cell', true, 'pt-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'PT'), '5GB · 30 Days', 5, 30, 14.5, 'Atlantico Cell', true, 'pt-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'PT'), '10GB · 30 Days', 10, 30, 23.0, 'Atlantico Cell', true, 'pt-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'NL'), '1GB · 7 Days', 1, 7, 5.5, 'Tulip Telecom', true, 'nl-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'NL'), '3GB · 15 Days', 3, 15, 10.5, 'Tulip Telecom', true, 'nl-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'NL'), '5GB · 30 Days', 5, 30, 16.0, 'Tulip Telecom', true, 'nl-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'NL'), '10GB · 30 Days', 10, 30, 25.5, 'Tulip Telecom', true, 'nl-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CH'), '1GB · 7 Days', 1, 7, 7.0, 'Alpine Signal', true, 'ch-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CH'), '3GB · 15 Days', 3, 15, 13.5, 'Alpine Signal', true, 'ch-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CH'), '5GB · 30 Days', 5, 30, 20.5, 'Alpine Signal', true, 'ch-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CH'), '10GB · 30 Days', 10, 30, 32.0, 'Alpine Signal', true, 'ch-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'AT'), '1GB · 7 Days', 1, 7, 5.5, 'Danube Data', true, 'at-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'AT'), '3GB · 15 Days', 3, 15, 10.5, 'Danube Data', true, 'at-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'AT'), '5GB · 30 Days', 5, 30, 16.0, 'Danube Data', true, 'at-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'AT'), '10GB · 30 Days', 10, 30, 25.5, 'Danube Data', true, 'at-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'GR'), '1GB · 7 Days', 1, 7, 5.0, 'Aegean Mobile', true, 'gr-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'GR'), '3GB · 15 Days', 3, 15, 9.5, 'Aegean Mobile', true, 'gr-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'GR'), '5GB · 30 Days', 5, 30, 14.5, 'Aegean Mobile', true, 'gr-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'GR'), '10GB · 30 Days', 10, 30, 23.0, 'Aegean Mobile', true, 'gr-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'IE'), '1GB · 7 Days', 1, 7, 5.5, 'Shamrock Net', true, 'ie-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'IE'), '3GB · 15 Days', 3, 15, 10.5, 'Shamrock Net', true, 'ie-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'IE'), '5GB · 30 Days', 5, 30, 16.0, 'Shamrock Net', true, 'ie-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'IE'), '10GB · 30 Days', 10, 30, 25.5, 'Shamrock Net', true, 'ie-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'PL'), '1GB · 7 Days', 1, 7, 4.5, 'Vistula Mobile', true, 'pl-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'PL'), '3GB · 15 Days', 3, 15, 8.5, 'Vistula Mobile', true, 'pl-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'PL'), '5GB · 30 Days', 5, 30, 13.0, 'Vistula Mobile', true, 'pl-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'PL'), '10GB · 30 Days', 10, 30, 20.5, 'Vistula Mobile', true, 'pl-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CZ'), '1GB · 7 Days', 1, 7, 5.0, 'Bohemia Link', true, 'cz-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CZ'), '3GB · 15 Days', 3, 15, 9.0, 'Bohemia Link', true, 'cz-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CZ'), '5GB · 30 Days', 5, 30, 14.0, 'Bohemia Link', true, 'cz-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CZ'), '10GB · 30 Days', 10, 30, 22.0, 'Bohemia Link', true, 'cz-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'US'), '1GB · 7 Days', 1, 7, 6.5, 'StarConnect', true, 'us-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'US'), '3GB · 15 Days', 3, 15, 12.5, 'StarConnect', true, 'us-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'US'), '5GB · 30 Days', 5, 30, 19.0, 'StarConnect', true, 'us-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'US'), '10GB · 30 Days', 10, 30, 30.0, 'StarConnect', true, 'us-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'US'), 'Unlimited · 30 Days', 999, 30, 47.0, 'StarConnect', true, 'us-30days-unlimited'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CA'), '1GB · 7 Days', 1, 7, 6.5, 'Maple Mobile', true, 'ca-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CA'), '3GB · 15 Days', 3, 15, 12.5, 'Maple Mobile', true, 'ca-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CA'), '5GB · 30 Days', 5, 30, 19.0, 'Maple Mobile', true, 'ca-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CA'), '10GB · 30 Days', 10, 30, 30.0, 'Maple Mobile', true, 'ca-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'CA'), 'Unlimited · 30 Days', 999, 30, 47.0, 'Maple Mobile', true, 'ca-30days-unlimited'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MX'), '1GB · 7 Days', 1, 7, 4.5, 'Azteca Net', true, 'mx-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MX'), '3GB · 15 Days', 3, 15, 8.5, 'Azteca Net', true, 'mx-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MX'), '5GB · 30 Days', 5, 30, 13.0, 'Azteca Net', true, 'mx-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MX'), '10GB · 30 Days', 10, 30, 20.5, 'Azteca Net', true, 'mx-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'BR'), '1GB · 7 Days', 1, 7, 5.0, 'Samba Signal', true, 'br-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'BR'), '3GB · 15 Days', 3, 15, 9.0, 'Samba Signal', true, 'br-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'BR'), '5GB · 30 Days', 5, 30, 14.0, 'Samba Signal', true, 'br-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'BR'), '10GB · 30 Days', 10, 30, 22.0, 'Samba Signal', true, 'br-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'AU'), '1GB · 7 Days', 1, 7, 6.0, 'OzConnect', true, 'au-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'AU'), '3GB · 15 Days', 3, 15, 11.5, 'OzConnect', true, 'au-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'AU'), '5GB · 30 Days', 5, 30, 17.5, 'OzConnect', true, 'au-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'AU'), '10GB · 30 Days', 10, 30, 27.5, 'OzConnect', true, 'au-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'AU'), 'Unlimited · 30 Days', 999, 30, 43.0, 'OzConnect', true, 'au-30days-unlimited'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'NZ'), '1GB · 7 Days', 1, 7, 6.0, 'Kiwi Connect', true, 'nz-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'NZ'), '3GB · 15 Days', 3, 15, 11.5, 'Kiwi Connect', true, 'nz-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'NZ'), '5GB · 30 Days', 5, 30, 17.5, 'Kiwi Connect', true, 'nz-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'NZ'), '10GB · 30 Days', 10, 30, 27.5, 'Kiwi Connect', true, 'nz-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'EG'), '1GB · 7 Days', 1, 7, 4.0, 'Nile Net', true, 'eg-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'EG'), '3GB · 15 Days', 3, 15, 8.0, 'Nile Net', true, 'eg-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'EG'), '5GB · 30 Days', 5, 30, 12.5, 'Nile Net', true, 'eg-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'EG'), '10GB · 30 Days', 10, 30, 19.5, 'Nile Net', true, 'eg-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ZA'), '1GB · 7 Days', 1, 7, 5.0, 'Savanna Cell', true, 'za-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ZA'), '3GB · 15 Days', 3, 15, 9.0, 'Savanna Cell', true, 'za-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ZA'), '5GB · 30 Days', 5, 30, 14.0, 'Savanna Cell', true, 'za-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ZA'), '10GB · 30 Days', 10, 30, 22.0, 'Savanna Cell', true, 'za-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MA'), '1GB · 7 Days', 1, 7, 4.5, 'Atlas Mobile', true, 'ma-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MA'), '3GB · 15 Days', 3, 15, 8.5, 'Atlas Mobile', true, 'ma-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MA'), '5GB · 30 Days', 5, 30, 13.0, 'Atlas Mobile', true, 'ma-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'MA'), '10GB · 30 Days', 10, 30, 20.5, 'Atlas Mobile', true, 'ma-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'KE'), '1GB · 7 Days', 1, 7, 4.5, 'Safari Signal', true, 'ke-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'KE'), '3GB · 15 Days', 3, 15, 8.5, 'Safari Signal', true, 'ke-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'KE'), '5GB · 30 Days', 5, 30, 13.0, 'Safari Signal', true, 'ke-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'KE'), '10GB · 30 Days', 10, 30, 20.5, 'Safari Signal', true, 'ke-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ASIA'), '3GB · 15 Days', 3, 15, 16.0, 'PanAsia Roam', true, 'asia-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ASIA'), '5GB · 30 Days', 5, 30, 24.0, 'PanAsia Roam', true, 'asia-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'ASIA'), '10GB · 30 Days', 10, 30, 39.0, 'PanAsia Roam', true, 'asia-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'EURO'), '3GB · 15 Days', 3, 15, 17.0, 'EuroLink Roam', true, 'euro-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'EURO'), '5GB · 30 Days', 5, 30, 26.0, 'EuroLink Roam', true, 'euro-30days-5gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'EURO'), '10GB · 30 Days', 10, 30, 42.0, 'EuroLink Roam', true, 'euro-30days-10gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'GLOBAL'), '1GB · 7 Days', 1, 7, 12.0, 'Orbit Global', true, 'global-7days-1gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'GLOBAL'), '3GB · 15 Days', 3, 15, 24.0, 'Orbit Global', true, 'global-15days-3gb'),
  (gen_random_uuid(), (SELECT id FROM countries WHERE code = 'GLOBAL'), '5GB · 30 Days', 5, 30, 36.0, 'Orbit Global', true, 'global-30days-5gb');

-- ---------- 6. Verify ----------
SELECT c.flag_emoji, c.name, count(p.id) AS plans, min(p.price_sgd) AS from_sgd
FROM countries c LEFT JOIN esim_plans p ON p.country_id = c.id
GROUP BY c.id, c.flag_emoji, c.name ORDER BY c.name;
